#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    start=n-1
    value=arr[start]
    while(arr[start-1] >= value):
        arr[start] = arr[start-1]
        start = start-1
        for i in arr:
            print(i,end=' ')
        print("")
        if(start == 0):
            arr[0]=value
            break
        else:
            arr[start] = value
    for i in arr:
        print(i,end=' ')
    
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
